<a href="https://colab.research.google.com/github/vasuans/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch Basics**

In [ ]:
import torch
import numpy as np

**Checking pyTorch version**

In [ ]:
torch.__version__

'1.6.0+cu101'

**Converting Numpy array to Torch tensor**

In [ ]:
arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

from_numpy is used to convert Numpy array to tensor.

In [ ]:
x= torch.from_numpy(arr)

In [ ]:
type(x)

torch.Tensor

In [ ]:
x

tensor([1, 2, 3, 4, 5])

In [ ]:
x.dtype

torch.int64

**Converting two dimentional numpy array to Tensor**

In [ ]:
arr2d = np.arange(0.0,12.0)

In [ ]:
arr2d = arr2d.reshape(4,3)

In [ ]:
x2 = torch.from_numpy(arr2d)

In [ ]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

**'from_numpy' keeps relation between original numpy array and tensor. Which means when you change any value in tensor that value gets updated in numpy array and vice versa.**

In [ ]:
arr[0]= 99

In [ ]:
x

tensor([99,  2,  3,  4,  5])

**tensor function can be used to avoid this relation. So basically .tensor will create a copy of numpy array.**


In [ ]:
my_arr = np.arange(0,10)

In [ ]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = torch.tensor(my_arr)

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Now even if we update original array, tensor will not get update**

In [ ]:
my_arr[0] = 99
my_arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Difference between **t**orch and **T**orch



*   Torch will create floating tensor.
*   torch will create integer tensor.





In [ ]:
new_arr = np.array([1,2,3])

In [ ]:
my_tensor = torch.Tensor(new_arr)

In [ ]:
my_tensor.dtype

torch.float32

In [ ]:
my_int_tensor = torch.tensor(new_arr)

In [ ]:
my_int_tensor.dtype

torch.int64

**Creating tensors from scrach using pyTorch**

In [ ]:
# Creating empty array for place holder
torch.empty(4,2)

tensor([[2.6355e-37, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 4.5731e+07],
        [1.1578e+27, 1.1362e+30]])

In [ ]:
#creating zero array
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Creating ones array
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#creating Range of values
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
#Reshape tensor
torch.arange(0,18,2).reshape(3,3)


tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
#Generate Linear values between two numbers
torch.linspace(0,18,12).reshape(4,3)

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

In [ ]:
my_tensor= torch.tensor([1,2,3])

In [ ]:
my_tensor.dtype

torch.int64

In [ ]:
# change datatype of tensor
my_tensor=my_tensor.type(torch.int32)

In [ ]:
my_tensor.dtype

torch.int32

In [ ]:
#Generate Random numbers
torch.rand(4,3)

tensor([[0.8766, 0.4394, 0.7636],
        [0.8563, 0.0520, 0.3943],
        [0.7226, 0.9149, 0.9641],
        [0.8014, 0.8792, 0.2943]])

In [ ]:
# Generate random standard distribution
torch.randn(4,3)

tensor([[-0.2985, -1.6604,  0.5627],
        [ 1.0410,  1.7555, -1.0045],
        [ 1.0719, -0.6975, -0.3069],
        [ 0.1395,  1.2338, -1.1950]])

In [ ]:
#Generate random number like another tensor
x=torch.zeros(2,5)
my_t = torch.rand_like(x)

In [ ]:
my_t

tensor([[1.4484e-01, 9.3758e-01, 4.1354e-04, 5.0174e-02, 8.6420e-01],
        [8.0414e-01, 7.9744e-01, 3.3768e-02, 1.4932e-01, 4.1417e-01]])

In [ ]:
#setting seed for randon values
torch.manual_seed(42)

In [ ]:
# Same random values will get generated every time
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# Generate randor integers between two numbers

torch.randint(low = 0, high = 11 , size = (5,5))

tensor([[ 3,  0,  8,  2,  1],
        [10,  3,  4,  2,  0],
        [ 4,  3,  6,  9, 10],
        [ 8,  9,  6,  3,  0],
        [ 1, 10,  3,  4,  3]])

# **Tensor Operations**

In [ ]:
#Reshape an array
x = torch.arange(6).reshape(3,2)

In [ ]:
#Get columns as array
x[:,1]

tensor([1, 3, 5])

In [ ]:
# get column as column array
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [ ]:
# View vs Reshape
